version: '3.5'
services:
  api1: # API - Instância 01
    build: 
      context: ./
      dockerfile: ./Dockerfile
    image: api
    hostname: api1
    depends_on:
      - postgres
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  api2: # API - Instância 02
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: api
    hostname: api2
    depends_on:
      - postgres
    expose:
      - "80"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  nginx: # Load Balancer
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api1
      - api2
    ports:
      - "9999:9999"
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '0.5GB'

  postgres: # Banco de dados
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/
      - ./configs/custom_postgresql.conf:/etc/postgresql/postgresql.conf
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    command: -c 'config_file=/etc/postgresql/postgresql.conf'
    deploy:
      resources:
        limits:
          cpus: '0.75'
          memory: '1.5GB'


volumes:
  pgdata: